---
  - name: Check if Aegir is installed
    shell: "[ -d /var/aegir/config ]"
    changed_when: False
    ignore_errors: True
    register: aegir_user_exists

  - name: Preseed Aegir hostmaster site url
    shell: echo "debconf aegir/site string {{ inventory_hostname }}" | debconf-set-selections
    when: aegir_user_exists|failed
  - name: Preseed Aegir hostmaster db_host
    shell: echo "debconf aegir/db_host string 127.0.0.1" | debconf-set-selections
    when: aegir_user_exists|failed
  - name: Preseed Aegir hostmaster db_user
    shell: echo "debconf aegir/db_user string root" | debconf-set-selections
    when: aegir_user_exists|failed
  - name: Preseed Aegir hostmaster db_password
    shell: echo "debconf aegir/db_password password `cat /root/.mysql.root`" | debconf-set-selections
    when: aegir_user_exists|failed

  - name: Install apt repo management packages
    apt: pkg={{ item }} state=installed update_cache=true
    with_items:
      - debian-keyring
      - debian-archive-keyring
      - python-software-properties
    register: basicaptpackagesinstalled

  - name: Install aegir3 repo apt key
    apt_key: url=http://debian.aegirproject.org/key.asc state=present
    when: basicaptpackagesinstalled|success
    register: aegir3keyinstalled
    # Bug in changed status when --check?
    changed_when: false

  - name: Install aegir3 repo
    apt_repository: repo='deb http://debian.aegirproject.org stable main' state=present
    when: aegir3keyinstalled|success
    register: aegir3repoinstalled

  - name: Install Aegir3
    apt: pkg=aegir3 state=installed update_cache=true
    register: aegir3installed
    when: aegir3keyinstalled|success
    notify:
      - Restart Apache
