---
  - name: Install nginx
    apt: pkg=nginx state=installed update_cache=true
    register: nginxinstalled
    notify:
     - Start webserver

  - name: Install PHP packages
    apt: pkg={{item}} state=installed update_cache=true
    with_items:
      - curl
      - php5
      - php5-curl
      - php5-gd
      - php5-mysql
    when: nginxinstalled|success
    register: php5installed
    notify:
     - Start webserver
