---
- hosts: aegir2
  roles:
    - aegir2

- hosts: aegir3
  roles:
    - aegir3

- hosts: munin-hosts
  roles:
    - munin-node

- hosts: munin-servers
  roles:
    - munin-server

- hosts: nagios-servers
  roles:
    - nagios-server

- hosts: nagios-hosts
  roles:
    - nagios-host
