---
- hosts: all
  roles:
    - web

- hosts: munin-hosts
  roles:
    - web
    - munin-node

- hosts: munin-servers
  roles:
    - web
    - munin-server

- hosts: nagios-servers
  roles:
    - nagios-server

- hosts: nagios-hosts
  roles:
    - nagios-host
