---
  - name: Install munin
    apt: pkg=munin state=installed update_cache=true
    register: muninserverinstalled
    # Not sure if we need to wait for Apache but better safe than sorry
    when: apache2installed|success
    notify:
      - Start munin server
      - Restart Apache

  - name: Enable Apache vhost
    when: muninserverinstalled|success
    file: src=/etc/munin/apache.conf dest=/etc/apache2/conf.d/munin owner=root group=root state=link
    notify:
      - Reload Apache

  - name: Create munin server agent config
    when: muninserverinstalled|success
    template: src=munin-agent.conf.j2 dest=/etc/munin/munin-conf.d/monitored-agents.conf owner=root group=root
    notify:
      - Restart munin server
