---
  - name: Install munin-node
    apt: pkg={{item}} state=installed update_cache=true
    with_items:
      - munin-node
      - munin-plugins-core
      - munin-plugins-extra
      # These perl libraries are needed for various munin plugins
      - libwww-perl
      - libdbd-mysql-perl
      - libcache-cache-perl
      - libcache-perl
    register: muninnodeinstalled
    # if there's no Apache, there's nothing to monitor
    when: apache2installed|success
    notify:
      - Start munin-node

  - name: Create Apache vhost
    when: muninnodeinstalled|success
    template: src=munin-stats dest=/etc/apache2/sites-available/munin-stats mode=775 owner=root group=root
    register: apachemuninvhostcreated
    notify:
      - Restart munin-node

  - name: Create munin plugin config
    when: muninnodeinstalled|success
    template: src=munin-node dest=/etc/munin/plugin-conf.d/munin-node mode=775 owner=root group=root
    notify:
      - Restart munin-node

  - name: Create munin node config
    when: muninnodeinstalled|success
    template: src=munin-node.conf.j2 dest=/etc/munin/munin-node.conf mode=775 owner=root group=root
    notify:
      - Restart munin-node

  - name: Enable Apache vhost
    when: apachemuninvhostcreated|success
    file: src=/etc/apache2/sites-available/munin-stats dest=/etc/apache2/sites-enabled/munin-stats mode=777 owner=root group=root state=link
    notify:
      - Reload Apache

  - name: Enable extra munin plugins
    file: src=/usr/share/munin/plugins/{{ item }} dest=/etc/munin/plugins/{{ item }} state=link
    with_items:
      - apache_accesses
      - apache_volume
      - apt
      - apt_all
      - mysql_queries
      - mysql_threads
      - mysql_slowqueries
    when: muninnodeinstalled|success
    notify:
      - Restart munin-node
