---
  - name: Install apt repo management packages
    apt: pkg={{ item }} state=installed update_cache=true
    with_items:
      - debian-keyring
      - debian-archive-keyring
      - python-software-properties
    register: basicaptpackagesinstalled

  - name: Install aegir2 repo apt key
    apt_key: url=http://debian.aegirproject.org/key.asc state=present
    when: basicaptpackagesinstalled|success
    register: aegir2keyinstalled

  - name: Install aegir2 repo
    apt_repository: repo='deb http://debian.aegirproject.org stable main' state=present
    when: aegir2keyinstalled|success
    register: aegir2repoinstalled

  - name: Install Aegir2
    apt: pkg=aegir2 state=installed update_cache=true
    register: aegir2installed
    when: aegir2keyinstalled|success
    notify:
      - Restart Apache
