---
  - name: Start Apache
    service: name=apache2 state=started

  - name: Reload Apache
    service: name=apache2 state=reloaded

  - name: Restart Apache
    service: name=apache2 state=restarted

  - name: Start MySQL
    service: name=mysql state=started
