---
  - name: Install nagios-nrpe-server
    apt: pkg={{item}} state=installed update_cache=true
    with_items:
      - nagios-nrpe-server
    register: nagiosnrpeserverinstalled
    notify:
      - Start nagios-nrpe-server

  - name: Create nrpe config
    when: nagiosnrpeserverinstalled|success
    template: src=praxis_nagios_aegirvps.cfg.j2 dest=/etc/nagios/nrpe.d/praxis_nagios_aegirvps.cfg mode=775 owner=root group=root
    notify:
      - Restart nagios-nrpe-server
