---
  - name: Install common packages
    apt: pkg={{ item }} state=installed update_cache=true
    with_items:
      - fail2ban
      - git
      - htop
      - ntp
      - npm
      - tree
      - vim
