---
  - name: Install common packages
    apt: pkg={{ item }} state=installed update_cache=true
    with_items:
      - fail2ban
      - git
      - htop
      - ntp
      - tree
      - vim

  # Create our users
  - user: name=gboudrias shell=/bin/bash
  - authorized_key: user=gboudrias key="{{ lookup('file', 'gboudrias.pub') }}"
