---
  - name: Install nagios
    apt: pkg={{item}} state=installed update_cache=true
    with_items:
      - nagios3
      - nagios-nrpe-plugin
    register: nagiosinstalled
    notify:
      - Start nagios

  - name: Create nagios config
    when: nagiosinstalled|success
    template: src=praxis_nagios.cfg.j2 dest=/etc/nagios3/conf.d/praxis_aegirvps_nagios_hosts.cfg mode=775 owner=root group=root
    notify:
      - Restart nagios
